### ISSUE TITLE
Make Twig breadcrumb helper as public

### ISSUE THREAD

**Issue by davidnectarestudio** [mhujer/BreadcrumbsBundle#41]
It is possible to make `white_october_breadcrumbs.helper` service as public?

**Comment by mhujer** [comment]
@davidnectarestudio It is public https://github.com/mhujer/BreadcrumbsBundle/blob/a2cde1f8cec423cedee8441410106bde24341675/Resources/config/breadcrumbs.xml#L19

**Comment by davidnectarestudio** [comment]
Thanks for your answer @mhujer but is not working for me (using default auto wiring).

```php
<?php

namespace App\Twig;

use App\Enum\RoutesEnum;
use App\Model\BreadcrumbDto;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;
use WhiteOctober\BreadcrumbsBundle\Model\Breadcrumbs;
use WhiteOctober\BreadcrumbsBundle\Templating\Helper\BreadcrumbsHelper;

final class AppExtension extends AbstractExtension
{
    private Serializer $serializer;

    public function __construct(
        private readonly Breadcrumbs $breadcrumbs,
        private readonly BreadcrumbsHelper $breadcrumbsHelper,
    ) {
        $this->serializer = new Serializer([new ObjectNormalizer()]);
    }
```

<img width="1053" alt="Captura de pantalla 2024-12-30 a les 9 21 16" src="https://github.com/user-attachments/assets/d6b00e9c-5070-403b-b00f-e93ad5e1a823" />

**Comment by davidnectarestudio** [comment]
Fixed with service alias definition

```yaml
# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # aliases
    WhiteOctober\BreadcrumbsBundle\Templating\Helper\BreadcrumbsHelper:
        alias: 'white_october_breadcrumbs.helper'
        public: true
```
